// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHpFkTw-E7F2E-SvUDWW1xvz6IQY3OxU8',
    appId: '1:1021683217555:web:58315985cca52f44064966',
    messagingSenderId: '1021683217555',
    projectId: 'scholar-chat-app-df1ec',
    authDomain: 'scholar-chat-app-df1ec.firebaseapp.com',
    storageBucket: 'scholar-chat-app-df1ec.appspot.com',
    measurementId: 'G-LKTSRY5VZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrx7Oblmr5FWyGEuiCeW-x8wuLdD-RpGM',
    appId: '1:1021683217555:android:0d3047cbfc980309064966',
    messagingSenderId: '1021683217555',
    projectId: 'scholar-chat-app-df1ec',
    storageBucket: 'scholar-chat-app-df1ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWtSeRjdAZGRTHOEH6_9LCNOl_C3Mz3iU',
    appId: '1:1021683217555:ios:90cf76fc1e2d47a3064966',
    messagingSenderId: '1021683217555',
    projectId: 'scholar-chat-app-df1ec',
    storageBucket: 'scholar-chat-app-df1ec.appspot.com',
    iosBundleId: 'com.example.scholarChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWtSeRjdAZGRTHOEH6_9LCNOl_C3Mz3iU',
    appId: '1:1021683217555:ios:060e936e42493fe2064966',
    messagingSenderId: '1021683217555',
    projectId: 'scholar-chat-app-df1ec',
    storageBucket: 'scholar-chat-app-df1ec.appspot.com',
    iosBundleId: 'com.example.scholarChatApp.RunnerTests',
  );
}
